
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-profit-margins
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finance-profit-margins
  template:
    metadata:
      labels:
        app: finance-profit-margins
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8000"
    spec:
      containers:
      - name: finance-profit-margins
        image: registry/finance/profit-margins:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        env:
        - name: PORT
          value: "8000"
---
apiVersion: v1
kind: Service
metadata:
  name: finance-profit-margins
spec:
  selector:
    app: finance-profit-margins
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
